name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          conda install -c conda-forge pandoc
          conda install -c conda-forge ipython
          pip install sphinxcontrib-websupport
          sudo apt update
          sudo apt install -y graphviz

      - name: Build the book
        run: |
          cd docs
          make gettext
          sphinx-intl update -p _build/gettext
          make html
          sphinx-build -D language=en -b html ./ _build/html/en

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"